apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cli
  name: cli
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cli
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cli
    spec:
      containers:
        - env:
            - name: COMPOSER_ALLOW_XDEBUG
              value: "0"
            - name: COMPOSER_DISABLE_XDEBUG_WARN
              value: "0"
            - name: DOCROOT
              value: web
            - name: DRUSH_ALLOW_XDEBUG
              value: "0"
            - name: DRUSH_OPTIONS_URI
              value: test-drupal9.docksal
            - name: GIT_USER_EMAIL
              value: bcmcveigh@gmail.com
            - name: GIT_USER_NAME
              value: Brian McVeigh
            - name: HOST_GID
              value: "137"
            - name: HOST_UID
              value: "1000"
            - name: MYSQL_DATABASE
              value: default
            - name: MYSQL_HOST
              value: db
            - name: MYSQL_PASSWORD
              value: user
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: user
            - name: SSH_AUTH_SOCK
              value: /.ssh-agent/proxy-socket
            - name: VIRTUAL_HOST
              value: test-drupal9.docksal
            - name: XDEBUG_CONFIG
              value: client_host=192.168.64.1 remote_host=192.168.64.1
            - name: XDEBUG_ENABLED
              value: "0"
          image: docksal/cli:php8.1-3.2
          name: cli
          ports:
            - containerPort: 80
          resources: {}
      hostname: cli
      restartPolicy: Always
status: {}
