apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: APACHE_DOCUMENTROOT
              value: /var/www/web
            - name: APACHE_FCGI_HOST_PORT
              value: cli:9000
          image: docksal/apache:2.4-2.5
          name: web
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
      hostname: web
      restartPolicy: Always
status: {}
